### ISSUE TITLE
Other games support

### ISSUE THREAD

**Issue by Azim** [nomnomab/lc-project-patcher#1]
How much of it is LC-specific? currently figuring out unity project setup for other game and thought this might come in handy.

**Comment by nomnomab** [comment]
I'd say a bit of the editor-side is LC-specific, but less so on the tool-side, such as the netcode __rpc/etc scrubbers, and the inner rpc-generated code scrubber. 

Although most of the in-editor parts that *are* LC-specific are mostly with some namings, which I don't think there are a ton of.
