### ISSUE TITLE
Would autostart mod work???

### ISSUE THREAD

**Issue by Cuphead74832** [nomnomab/lc-project-patcher#11]
There is this mod which allows anything to autopull the lever but i dont know if it will work with the patcher since the way that does it is weird could you tell me if you can get this mod to do its thing out of the box?? https://www.youtube.com/watch?v=F15LVSVIWNU Feel free to send screenshots

**Comment by nomnomab** [comment]
Sorry I don't have time to test this sort of stuff, you can test it on your end and if it doesn't work, then you can use something else 👍
