### ISSUE TITLE
After pacthering，all of the Scripts is Unavailable！

### ISSUE THREAD

**Issue by apeng0907** [nomnomab/lc-project-patcher#3]
the associated script can not be loaded please fix any compile error and and assgin a vaild script
![image](https://github.com/nomnomab/lc-project-patcher/assets/125883521/3778517e-9428-4180-b1da-9fd1ba1256f2)

**Comment by apeng0907** [comment]
And it generated 999+errors
![image](https://github.com/nomnomab/lc-project-patcher/assets/125883521/87ce1bf8-0d0a-45ce-bc78-be5cd61b002e)

**Comment by nomnomab** [comment]
Hello, while it is good to show these errors, none of them are particularly useful.

Can you do the following?
- List steps taken to get here, or record a video of your screen so I can see in context.
- Did you follow the [instruction video](https://discord.com/channels/1168655651455639582/1199473521265475745/1212223298574745651) linked in the discord?
- or Did you follow the [steps](https://github.com/nomnomab/lc-project-patcher?tab=readme-ov-file#usage) on this github repo?
- Did you get an actual error that ended the patcher process early?

Thanks!

**Comment by apeng0907** [comment]
![image](https://github.com/nomnomab/lc-project-patcher/assets/125883521/feaf0d52-40bb-4f9d-b3e9-46382fc6cd72)
When I completed this step and restarted, these errors appeared

**Comment by apeng0907** [comment]
Can you package and send me the contents of these two folders？
Assets\LethalCompany\Game\Scripts
Assets\LethalCompany\Game\Plugins

**Comment by nomnomab** [comment]
> Can you package and send me the contents of these two folders？ Assets\LethalCompany\Game\Scripts Assets\LethalCompany\Game\Plugins

No I cannot, as that would be distributing game assets. 

However, something you can try is opening the tool (same location as step 3), clicking the Utility dropdown, and clicking the install button for the packages on the right-side. As it seems like they didn't install for you? Just a guess with the limited information here.

If that doesn't work, then I'll need a video of you running the tool in a **new** HDRP project, as well as the log file that produces (open the console window, right click the console tab and click Editor Log).

If you haven't watched the video linked above, I'd highly recommend watching it, as the first 8 minutes is a tutorial for this tool 👍

**Comment by apeng0907** [comment]
[Editor.log](https://github.com/nomnomab/lc-project-patcher/files/14462122/Editor.log)

**Comment by apeng0907** [comment]
yes,I have tried the methods in the video three times, and the results are all like this

**Comment by nomnomab** [comment]
All of the errors in the log are pertaining to the packages. Install them with the instructions above.

If it still has issues after, send me a video with a new HDRP project running the tool from start to finish.

**Comment by apeng0907** [comment]
Can you tell me your email？thanks

**Comment by nomnomab** [comment]
`nomnomab1@gmail.com`

**Comment by apeng0907** [comment]
OK，I have already sent the video

**Comment by nomnomab** [comment]
Ok so it seems the package installer doesn't seem to be properly installing the packages for you... somehow? (That step completed instantly so it seems like it got some false results or something).

I'll take a look at it, as everything else *seems* to have ran fine.

In that project you made a video of, can you expand the utility dropdown in the tool and show me the package list it has?

**Comment by apeng0907** [comment]
There are two differences from the video. One way is to install the LC project catcher is through unpacking the package. Another possibility is that it may be the installation of Git, as there is no detailed selection and introduction, it has always been the default installation method.

**Comment by apeng0907** [comment]
![image](https://github.com/nomnomab/lc-project-patcher/assets/125883521/7bcc9e2f-2aa4-404c-93d4-ae637e00b078)

**Comment by apeng0907** [comment]
![image](https://github.com/nomnomab/lc-project-patcher/assets/125883521/ca5ba4d0-c372-457e-9f01-aa2583dd27de)

**Comment by apeng0907** [comment]
I cannot use Add package from git URL. Because when I click add, there is no response

**Comment by apeng0907** [comment]
![image](https://github.com/nomnomab/lc-project-patcher/assets/125883521/60071541-ca58-4bad-b968-1472c29994b6)
So I downloaded the zip file from here

**Comment by nomnomab** [comment]
> In that project you made a video of, can you expand the utility dropdown in the tool and show me the package list it has?

I'm asking you to show me this:

![image](https://github.com/nomnomab/lc-project-patcher/assets/28305689/ffc028e8-6f7f-4e1b-a0c7-7dc0872fa93f)

**Comment by nomnomab** [comment]
> I cannot use Add package from git URL. Because when I click add, there is no response

What does "no response" mean here? Is there an error in the console?

**Comment by apeng0907** [comment]
![image](https://github.com/nomnomab/lc-project-patcher/assets/125883521/160b8cae-f390-4c42-b69a-38d7df158d60)

**Comment by nomnomab** [comment]
Ok so they *aren't* getting installed for some reason...

Does clicking install there (the button highlighted) put anything in the console?

**Comment by apeng0907** [comment]
![image](https://github.com/nomnomab/lc-project-patcher/assets/125883521/3f53b4dd-fe92-4861-add8-32e1aaca6877)

**Comment by apeng0907** [comment]
![image](https://github.com/nomnomab/lc-project-patcher/assets/125883521/072e801b-b901-4634-b76c-dde7a570cac2)

**Comment by nomnomab** [comment]
Ok so the package manager API is just lying I guess.

Can you head to `[ProjectName]\Packages\manifest.json` and send me the file contents so I can see if there is anything different about yours?

After that, see if this works on your end (you'll need to replace the `com.nomnom.lc-project-patcher` one with the one you have):

```json
{
  "dependencies": {
    "com.nomnom.lc-project-patcher": "file:C:/Users/nomno/Documents/Unity/2022.3.11f1/HDRP/LethalElevators/Assets/_Helpers/LCProjectValidator",
    "com.unity.ai.navigation": "1.1.5",
    "com.unity.animation.rigging": "1.2.1",
    "com.unity.assetbundlebrowser": "https://github.com/Unity-Technologies/AssetBundles-Browser.git",
    "com.unity.collab-proxy": "2.2.0",
    "com.unity.collections": "1.2.4",
    "com.unity.feature.development": "1.0.1",
    "com.unity.inputsystem": "1.7.0",
    "com.unity.netcode.gameobjects": "1.5.2",
    "com.unity.probuilder": "5.1.1",
    "com.unity.render-pipelines.high-definition": "14.0.8",
    "com.unity.textmeshpro": "3.0.6",
    "com.unity.timeline": "1.7.5",
    "com.unity.ugui": "1.0.0",
    "com.unity.visualscripting": "1.9.0",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}
```

This may need a new project to handle the script guids that were not present during the initial patch, but let's just see if they get properly loaded from this.

**Comment by apeng0907** [comment]
[manifest.json](https://github.com/nomnomab/lc-project-patcher/files/14463779/manifest.json)

**Comment by apeng0907** [comment]
Thank you very much

**Comment by apeng0907** [comment]
![image](https://github.com/nomnomab/lc-project-patcher/assets/125883521/ecd7f669-ca6c-4c45-a555-02a4d22586de)
After replacing the content of my personal manifest.json file, it displays this

**Comment by apeng0907** [comment]
![image](https://github.com/nomnomab/lc-project-patcher/assets/125883521/f5ba6374-dfad-4cb8-9d59-181894ee8405)
But I actually installed git

**Comment by apeng0907** [comment]
![image](https://github.com/nomnomab/lc-project-patcher/assets/125883521/a83ab286-b33d-49a6-bb1e-8482e0dd1653)
Is this the reason why git was not fully installed

**Comment by apeng0907** [comment]
![image](https://github.com/nomnomab/lc-project-patcher/assets/125883521/4ddd7f06-2ddb-472f-aa0d-2597311d56f8)
I am trying to “run pacther” again

**Comment by apeng0907** [comment]
![image](https://github.com/nomnomab/lc-project-patcher/assets/125883521/cc751968-5f11-491a-aed2-317fbd108534)

**Comment by apeng0907** [comment]
![image](https://github.com/nomnomab/lc-project-patcher/assets/125883521/9a7a6b01-caba-4a5d-b05f-4844d994890a)

**Comment by apeng0907** [comment]
![image](https://github.com/nomnomab/lc-project-patcher/assets/125883521/55c0d530-5f2e-489a-acb1-8ef7588cb423)

**Comment by apeng0907** [comment]
Can I ignore those errors and continue making my planet

**Comment by nomnomab** [comment]
Have you installed git recently, and have you restarted your pc or restarted Unity & Unity Hub since then? Otherwise it won't update it for Unity and it will think you don't have it.

Either way, that git package in the manifest is just for building asset bundles easily, so if git just doesn't play nice on your machine then you can remove it from the manifest file, and build them in whatever way you prefer.

**Comment by apeng0907** [comment]
Thank you very much for your patient answer. I have learned a lot during the communication process!
It should be due to network issues that I am unable to use Git properly,
In the end, I used Git to input the following code and then restarted the Unity Hub to resolve the issue
**git config --global http.proxy http://127.0.0.1:7890**

**Comment by apeng0907** [comment]
I'm very sorry to bother you again. After I went to build through assetbundles, I entered the game in the editor and entered moons, but couldn't find my planet

**Comment by nomnomab** [comment]
I don't know much about custom moons and such (I just make the editor tools), so if you are using something like LLL, I'd ask Batby in his discord thread about it. 

You can find that here: https://discord.com/channels/1168655651455639582/1193461151636398080

**Comment by apeng0907** [comment]
With your help, I made my first moon, thank you very much!
https://thunderstore.io/c/lethal-company/p/Apeng/PengCity/
I want to continue improving it, so I would like to ask if you have any usage introductions or use cases about other components, as I want to do some triggering events in the map
