### ISSUE TITLE
Please make it family friendly for linux users.

### ISSUE THREAD

**Issue by Cuphead74832** [nomnomab/lc-project-patcher#4]
I keep getting an error about win not being able to execute AssetRipper executable but i am on linux please fix it.

**Comment by Cuphead74832** [comment]
Basically just add a checkmark (outside of utilities) that says "Linux mode" so instead it downloads AssetRipper for Linux. After that a popup will appear telling you the location of the "AssetRipper" saying "Before continuing please give the AssetRipper executable permisions to execute the program. The program is located at //LOCATION// then press OK to continue" so the user has time to run chmod. Can you please make it fast i am on V45 and i wanna use it to test the patcher before updating as this is my favorite version and is the one i want to use for testing but i have to update soon to play with my bros. Also does the "Utility" dropdown gets locked until you succesfully run the patcher? Because i cant open it. (MOUSE TYPE: singular trackpad BUTTONS: One (left click only) RIGHTCLICK: Double Tap). I can also proof that i own a LEGIT copy on steam if you are sus out of the outdated version.

**Comment by nomnomab** [comment]
I don't download asset ripper, it's embedded in the package. I only download the dll from my Asset Ripper fork (in its Releases) since it's too large to store in the repository itself. 

I also don't have Linux, so I don't have a way to test/build AR for Linux at the moment (don't know if the net project can even be built for it out of the box?).

**Comment by Cuphead74832** [comment]
Well if i am able to proof that i have an steam account with a LEGIT copy by friending you to confirm i indeed have a copy and pass you the DATA folder only through mail and sending the project files back with a password (TO PREVENT ILLEGAL DISTRIBUTION) via email would you be able to do it for me?

If you accept send your email as this process would most likely want to make it private. (I AM WILLING TO ONLY SEND THE "DATA" I WONT SEND MONOBLEDDINGEDGE FOLDERS, EXE etc...)

**Comment by Cuphead74832** [comment]
I really need this. I only have this PC with linux no windows. VM? i already tried unity crashes and i been trying for 4 days now. 

(i use proton to play)

**Comment by Cuphead74832** [comment]
I am changing threats for a new idea.
