### ISSUE TITLE
How do i get the current version as of 12/03/2024? (not latest)

### ISSUE THREAD

**Issue by Cuphead74832** [nomnomab/lc-project-patcher#5]
Its me again the linux guy and i have a plan in summer my bro comes to my house for vacation during that time he lets me use his windows PC for stuff that wine cant run and so i have decided to use the tool in his computer when he comes. Since that is a long wait i already updated my V45 to latest which is V49 by the time im writing this and i backed up V45 since its the version i want to try to use and the V49 which again is the latest which should work great if V45 does not and can leave automatic updates enabled. But until summer there is a long time and a chance that V50 will drop with a BUNCH of features into it probably having to write and modify a LOT of the tools code on the future that might make V45 unusuable and so i saw that there is a way on the README to download an specific version of the tool. So if i wanted to download the current version as of the date that i mentioned on the title of the issue how do i have to type the URL? Please leave an easy to copy and paste response and close this issue as my weekend is over and i have to do my work.

(Also i recommend for linux testing to get a cheap VPS or something like that)

**Comment by nomnomab** [comment]
If you want a specific version of this tool, it's shown in the readme [here](https://github.com/nomnomab/lc-project-patcher?tab=readme-ov-file#installation).

Basically append the package version onto the end of the git link like:
```
https://github.com/nomnomab/lc-project-patcher.git#v1.2.3
```

You can find that version in the `package.json` file [here](https://github.com/nomnomab/lc-project-patcher/blob/master/package.json).

If you don't specific the version, then when you press "Update" in the package manager it will pull the latest version for you.

I hope this answers your question, if it doesn't, feel free to let me know! 👍

**Comment by Cuphead74832** [comment]
Reminder to my future self: The JSON looked like this at 12/03/2024

`{
  "name": "com.nomnom.lc-project-patcher",
  "version": "0.4.6",
  "displayName": "Lethal Company Project Patcher",
  "description": "A tool to generate a usable Unity project for Lethal Company modding.",
  "unity": "2022.3",
  "unityRelease": "9f1",
 "keywords": [],
  "author": {
    "name": "Andrew Burke",
    "email": "",
    "url": ""
  }
}`
