### ISSUE TITLE
[INTERNAL QUESTION NOT AN ISSUE] - How does the game comunicates when LAN?

### ISSUE THREAD

**Issue by Cuphead74832** [nomnomab/lc-project-patcher#6]
I am posting this here because if someone managed to make a decompiler they might know the answer. Basically i am wondering  how does lethal LAN communicates. By that i mean how does the client handshakes the host? Is it in JSON? and how does it communicate. 

I am trying to create a NodeJS short program that will just make the game think its an actual game server and atleast make it to the ship. Then try to land that ship and do stuff but we start basic by making it to lobby.

If you creator or someone else knows this answer please leave the handshake request as JSON (if its a JSON of course otherwise i wont mind if you tell me the request type) and the way to communicate to game in your comment so i can try.

**Comment by nomnomab** [comment]
For LAN the game uses Unity's Transport (and for online it uses the Facepunch Transport instead). 

![image](https://github.com/nomnomab/lc-project-patcher/assets/28305689/1cbb6087-cd01-419e-be7c-6b964a39b329)

I'm not super network savvy, so not sure about the handshake stuff, but hopefully that helps you find info into what you are wanting.

**Comment by ArjixWasTaken** [comment]
I am also interested in making a dedicated server!

~~But would NodeJS be the best for such a thing?~~
~~A compiled language like Go or Rust might be better.~~

Edit: since we know nothing about the unity transport, ig a prototype in nodejs would be ok.

**Comment by ArjixWasTaken** [comment]
I made the game connect to my udp server (using a custom made mod), and this is what it sends when it tries to connect.
![image](https://github.com/nomnomab/lc-project-patcher/assets/53124886/86c8a2ad-4958-4ade-af7e-09f0b6de8a90)

It is displayed in hex because it is not a string.
Note that the payload is different after every connection, indicating that it is a generated value, like an ID.

**Comment by ArjixWasTaken** [comment]
From my small investigation, it appears to be sending this structure.
![image](https://github.com/nomnomab/lc-project-patcher/assets/53124886/152d47ad-6b86-4dec-8e52-2d66a662cccc)

Or at least that is what unity provides to the developer upon a request.

**Comment by ArjixWasTaken** [comment]
~~I failed to parse that structure, it may be encoded in some way I am not aware of.~~
~~Nevermind, that structure is initialised in code, the payload can be anything the game developer wants it to be!~~
Nevermind yet again, it is serialized/deserialized by unity.

**Comment by ArjixWasTaken** [comment]
Aha!

The 10 byte message is a UDP Header!

```cs
namespace Unity.Networking.Transport.Protocols
{
	// Token: 0x020000A6 RID: 166
	internal struct UdpCHeader
	{
		// Token: 0x0400022C RID: 556
		public const int Length = 10;

		// Token: 0x0400022D RID: 557
		public byte Type;

		// Token: 0x0400022E RID: 558
		public UdpCHeader.HeaderFlags Flags;

		// Token: 0x0400022F RID: 559
		public SessionIdToken SessionToken;

		// Token: 0x020000A7 RID: 167
		[Flags]
		public enum HeaderFlags : byte
		{
			// Token: 0x04000231 RID: 561
			HasConnectToken = 1,
			// Token: 0x04000232 RID: 562
			HasPipeline = 2
		}
	}
}
```

**Comment by ArjixWasTaken** [comment]
Now I call this some progress, hehe
![image](https://github.com/nomnomab/lc-project-patcher/assets/53124886/da302c03-c884-467b-8c14-243c700d445d)

I made a discord server for further progress reports and general communication.
https://discord.gg/UhtkBJv9dQ

Edit: [Here](https://github.com/ArjixWasTaken/lc-dedicated-server) is the repo as well!

**Comment by Cuphead74832** [comment]
> Now I call this some progress, hehe ![image](https://private-user-images.githubusercontent.com/53124886/313514154-da302c03-c884-467b-8c14-243c700d445d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTUxMDIsIm5iZiI6MTcxMDc5NDgwMiwicGF0aCI6Ii81MzEyNDg4Ni8zMTM1MTQxNTQtZGEzMDJjMDMtYzg4NC00NjdiLThjMTQtMjQzYzcwMGQ0NDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDIwNDY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMTJlOTAyNGRhZWFhMDIwMGVmYzc2MTZmNjcyMGMwMWY5YTZhYzMxNmY3YzY2YzNhMGU1MTg5OTEzMGE5MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MQhaKGgz2KkbWs2GQl2aMZgtWLQjV75sjPsFJG-XynM)
> 
> I made a discord server for further progress reports and general communication. https://discord.gg/UhtkBJv9dQ
> 
> Edit: [Here](https://github.com/ArjixWasTaken/lc-dedicated-server) is the repo as well!

HOLY ****** DUDE.

**Comment by Cuphead74832** [comment]
Guys keep this issue opened this is indeed not an issue this is progress that shows the power of the project. Someone is managing to make a dedicated (somehow) server and i want this to be opened for him to keep updating its progress.
