### ISSUE TITLE
Patcher settings blocked?

### ISSUE THREAD

**Issue by Cuphead74832** [nomnomab/lc-project-patcher#8]
Hey dude i am having the next issue 

*blocked: "Assets/LCPatcherRuntimeSettings.asset"
UnityEngine.Debug:LogWarning (object)
Nomnom.LCProjectPatcher.Editor.AssetModificationBlocker:OnWillSaveAssets (string[]) (at ./Library/PackageCache/com.nomnom.lc-project-patcher@c88acc6fb1/Editor/AssetModificationBlocker.cs:70)
UnityEditor.AssetModificationProcessorInternal:OnWillSaveAssets (string[],string[]&,string[]&,bool)
Nomnom.LCProjectPatcher.Editor.AssetModificationBlocker:OnPlayModeStateChanged (UnityEditor.PlayModeStateChange) (at ./Library/PackageCache/com.nomnom.lc-project-patcher@c88acc6fb1/Editor/AssetModificationBlocker.cs:35)
UnityEditor.EditorApplication:Internal_PlayModeStateChanged (UnityEditor.PlayModeStateChange) (at /home/bokken/build/output/unity/unity/Editor/Mono/EditorApplication.cs:444)*

Also there are minor questions in the discord server check my pings, i wont tell those question here to keep the issues section clean.

**Comment by nomnomab** [comment]
That's not an issue. That's saying an asset was modified, and was detected when the play mode state changed so it reverted the changes to it (otherwise some assets get stuff missing from some mods removing things).

So this isn't an issue 👍
