### ISSUE TITLE
Base game always needed??

### ISSUE THREAD

**Issue by Cuphead74832** [nomnomab/lc-project-patcher#9]
If the project has been moved from computer to computer is the base game in the other computer need to be present??

**Comment by nomnomab** [comment]
No, the game is only required for extracting the assets/scripts/etc for patching.

Also, if someone else extracts the assets _for_ you, it is piracy, and this tool isn't made for that. 👍

**Comment by Cuphead74832** [comment]
I dont pirate :) i can screenshare to prove its much more legit than images

**Comment by Cuphead74832** [comment]
POV: Someone Pirated
Me: 
![me](https://github.com/nomnomab/lc-project-patcher/assets/119815517/3b1b501b-b9db-4b9b-81ce-a8df7f5809c0)
